version: "3.1"


services:
  
  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nest


  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs

  frontend:
    build : ./wm_frontend

  backend:
    build : ./wm
    depends_on:
      - db


  adminer:
    image: adminer
    restart: always

  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq


  quarkus:
    build:
      context: ./quarkus
      dockerfile : src/main/docker/Dockerfile.native
    container_name: quarkus
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      
  smtp:
    image: soulteary/maildev
    ports:
      - "1080:1080"

  prometheus:
    image: prom/prometheus
    depends_on:
      - backend
      - quarkus
      - rabbitmq
    volumes:
      - prometheus-data:/Prometheus
      - ./Monitoring/Prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/Prometheus'
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./Monitoring/Grafana/grafanaDashboard.yaml:/etc/grafana/dashboards/grafanaDashboard.yaml
      - ./Monitoring/Grafana/grafanaDatasource.yaml:/etc/grafana/provisioning/datasources/grafanaDatasource.yaml

volumes:
  grafana-data: 
  grafana-config: 
  grafana-dashboards: 
  prometheus-data: